require("config.lsps.clangd")
require("config.lsps.gopls")
require("config.lsps.rust-analyzer")
require("config.lsps.pyright")
require("config.lsps.lua_ls")
require("config.lsps.gdscript")
require("config.lsps.texlab")
require("config.lsps.yamlls")
